# tasks file for haproxy
---
- name: install | dependencies
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ haproxy_dependencies }}"
  tags:
    - haproxy-install-dependencies
