---
- name: SSH key
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Generate SSH id_rsa key
      command : ssh-keygen -t rsa -f /root/.ssh/id_rsa -q -P ""
      args:
        creates: /root/.ssh/id_rsa
      when: ansible_user_id == "root"

    - name: Generate SSH id_rsa key
      command : ssh-keygen -t rsa -f /home/{{username_on_the_host}}/.ssh/id_rsa -q -P ""
      args:
        creates: /home/{{username_on_the_host}}/.ssh/id_rsa
      when: ansible_user_id != "root"

- name: local (admin) node setup
  hosts: 127.0.0.1
  connection: local
  roles:
    - { role: java}
    - { role: nexus3}
    - { role: bootstrap-centos}
    - { role: ulimit}
    - { role: docker}
    - { role: registry}
    - { role: kubespray}

- name: Local haproxy setup - settings file
  hosts: 127.0.0.1
  connection: local
  tasks:
    # HAProxy cannot bind socket [0.0.0.0:8888]
    - name: modify the settings on selinux, all available ports became bind-able
      command: setsebool -P haproxy_connect_any=1
      become: yes
      ignore_errors: yes
    - name: Generating haproxy settings file
      template:
        src: haproxy-settings.yml.j2
        dest: /tmp/haproxy-settings.yml

    - name: Dynamically loading haproxy settings
      include_vars: /tmp/haproxy-settings.yml
    - include_role:
        name: haproxy

    - name: Removing the haproxy settings file
      file: path='/tmp/haproxy-settings.yml' state=absent

- name: setup all nodes
  hosts: all
  roles:
    - { role: bootstrap-centos}
    - { role: prerequisites}
    - { role: restart}
