---
- name: SSH key
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Kubectl get pods in json format
      kubectl: action=get type=pods output=wide
      register: output

    - debug: var=output.msg

- name: setup storage node
  hosts: all
  roles:
    - { role: prepare-nodes}

