---
- name: SSH key
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
    - name: Kubectl get pods in json format
      kubectl: action=get type=pods output=wide
      register: output

    - debug: var=output.msg
