---
- name: setup storage node
  hosts: all
  roles:
    - { role: prepare-nodes}

- name: Deploy Rook EdgeFS Cluster
  hosts: 127.0.0.1
  connection: local
  vars:
    edgefs_dir: rook/cluster/examples/kubernetes/edgefs
  tasks:
    - name: Deploy operator.yaml
      shell: "kubectl apply -f {{edgefs_dir}}/operator.yaml"

    - name: Deploy cluster.yaml
      shell: "kubectl apply -f {{edgefs_dir}}/cluster.yaml"

    - name: Get the edgefs-mgr pod
      shell: "kubectl get po --all-namespaces | grep edgefs-mgr"
      register: get_po_output
    
    - set_fact:
      pod_id: "{{ get_po_output | regex_replace('(rook-edgefs-mgr[0-9a-z\-]+)', '\\1') }}"

    - name: initialize edgefs cluster - login to the toolbox
      shell: "kubectl exec -it -n rook-edgefs {{pod_id}} -- env COLUMNS=$COLUMNS LINES=$LINES TERM=linux toolbox"
#
# TODO: run
#   init-edgefs-cluster.sh
#
    - name: Create NFS CRDs - reference edgefs service "nfs01"
      shell: "kubectl apply -f {{edgefs_dir}}/nfs.yaml"

    - name: Create kubernetes secret for NexentaEdge CSI plugin
      shell: "kubectl create secret generic rook-edgefs-cluster --from-file={{edgefs_dir}}/csi/secret/cluster-config.json"

    - name: Deploy EdgeFS CSI plugin, provisioner and attacher
      shell: "kubectl apply -f {{edgefs_dir}}/csi/."
