#!/bin/bash
#
set -e

OS_VERSION=$(grep -oE '[0-9]+\.[0-9]+' /etc/redhat-release)

# add docke repo
sudo curl -sSL https://download.docker.com/linux/centos/docker-ce.repo -o /etc/yum.repos.d/docker-ce.repo

[ ! -d docker-ce ] || rm -r -f docker-ce

mkdir docker-ce
cd docker-ce

sudo yum clean all
sudo yum install -y policycoreutils

# download docker-ce
sudo yumdownloader -q --nogpgcheck --resolve  --downloadonly docker-ce yum-utils device-mapper-persistent-data lvm2

# tar
tar cf docker-ce.offline-${OS_VERSION}.tar *.rpm

cp docker-ce.offline-${OS_VERSION}.tar ../../../files/
cd ..
rm -r -f docker-ce

