---
# For test scenarios, if you delete a cluster and start a new cluster on
# the same hosts, the path used by dataDirHostPath must be deleted.
# Otherwise, stale information and other config will remain from the
# previous cluster and the new target will fail to start.
#
# The path on the host (hostPath) where config and data should be stored for each of the services. If the directory does not exist, it will be created. 
#
- name: Removing existing dataDirHostPath
  file:
    path: "{{dataDirHostPath}}"
    state: absent

- name: ansible create directory for bind-mount (directory)
  file:
    path: "{{storage_directory}}"
    state: directory

- name: ansible create directory for bind-mount (mount point)
  file:
    path: "{{mount_point}}"
    state: directory

- name: Bind mounting /var/lpv into /mnt/disks/lpv
  lineinfile:
    path: /etc/fstab
    state: present
    line: "{{storage_directory}}   {{mount_point}}    none    bind"
  become: yes

- name: mount all filesystems mentioned in fstab
  command: mount -a
  become: yes

- name: install rpcbind for NFS mount
  yum:
    name: rpcbind
  become: yes

- name: start service rpcbind, if not running
  service:
    name: rpcbind
    state: started
  become: yes
