#!/bin/bash
#
set -e
#
source user.rc
#
echo Remote User: $USER
echo become-user: $BECOME_USR
echo Inventory: ${INVENTORY_DIVISION_DIR}
#
pushd ../kubespray-work-dir/
ansible-playbook -i ../inventory/${INVENTORY_DIVISION_DIR}/hosts.ini -u $USER --become --become-user=$BECOME_USR -e @../provisioner/kubespray-vars-overriding.yml cluster.yml
popd
